trigger:
  - maain

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.20.3"
    displayName: "Install Node.js"
  - script: |
      npm install
      npm run build
      npm run test
    displayName: "Install dependencies, build and test"
